GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikpvc2VUZXN0IiwiaWF0IjoxNjkzMzU5NjU3LCJleHAiOjE2OTMzNjAyNTd9.g9YQKptUBkEN_Fc_okPlU9NnAuceGFRbogvtVnIya08

###

DELETE http://localhost:3000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikpvc2VUZXN0IiwiaWF0IjoxNjkzMzU5NjU3LCJleHAiOjE2OTMzNjAyNTd9.g9YQKptUBkEN_Fc_okPlU9NnAuceGFRbogvtVnIya08"
}

###
POST http://localhost:3000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikpvc2VUZXN0IiwiaWF0IjoxNjkzMzU5NjU3fQ.nW_325ISif3FD4-9B0XnoI7EldbM7lohhbO6kMlIZPs"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "JoseTest",
    "password": "P@ssW0rd!"
}

###

POST http://localhost:4000/signup
Content-Type: application/json

{
    "username": "JoseTest",
    "password": "P@ssW0rd!"
}